- color_mean:
  - 0.5176527537723367
  - 0.4356887322413984
  - 0.35999143909760434
  color_std:
  - 0.364505717666511
  - 0.2801620218041305
  - 0.21222795915270712
  file_len: 233437
  filepath: /home/samanti/Desktop/data_practice/processed/0040_00.npy
  raw_description_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0040_00/scene0040_00.txt
  raw_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0040_00/scene0040_00_vh_clean_2.ply
  raw_instance_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0040_00/scene0040_00.aggregation.json
  raw_label_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0040_00/scene0040_00_vh_clean_2.labels.ply
  raw_segmentation_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0040_00/scene0040_00_vh_clean_2.0.010000.segs.json
  scene: 40
  scene_type: Office
  sub_scene: 0
# - color_mean:
#   - 0.5017989937007279
#   - 0.46473407725185284
#   - 0.43343039684998413
#   color_std:
#   - 0.312551307072343
#   - 0.26682425696349094
#   - 0.23555545399448638
#   file_len: 108419
#   filepath: /home/samanti/Desktop/data_practice/processed/0009_00.npy
#   raw_description_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0009_00/scene0009_00.txt
#   raw_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0009_00/scene0009_00_vh_clean_2.ply
#   raw_instance_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0009_00/scene0009_00.aggregation.json
#   raw_label_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0009_00/scene0009_00_vh_clean_2.labels.ply
#   raw_segmentation_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0009_00/scene0009_00_vh_clean_2.0.010000.segs.json
#   scene: 9
#   scene_type: Bathroom
#   sub_scene: 0
# - color_mean:
#   - 0.17961764946150788
#   - 0.1703043391720249
#   - 0.1375080184320453
#   color_std:
#   - 0.0802090957237917
#   - 0.06963106503584125
#   - 0.050053630112769455
#   file_len: 232583
#   filepath: /home/samanti/Desktop/data_practice/processed/0041_00.npy
#   raw_description_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0041_00/scene0041_00.txt
#   raw_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0041_00/scene0041_00_vh_clean_2.ply
#   raw_instance_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0041_00/scene0041_00_vh_clean.aggregation.json
#   raw_label_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0041_00/scene0041_00_vh_clean_2.labels.ply
#   raw_segmentation_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0041_00/scene0041_00_vh_clean_2.0.010000.segs.json
#   scene: 41
#   scene_type: Classroom
#   sub_scene: 0
# - color_mean:
#   - 0.5071190836766559
#   - 0.4784169656604914
#   - 0.44698122535901874
#   color_std:
#   - 0.3388782426829752
#   - 0.3023818983705169
#   - 0.2692643486259304
#   file_len: 173392
#   filepath: /home/samanti/Desktop/data_practice/processed/0025_00.npy
#   raw_description_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0025_00/scene0025_00.txt
#   raw_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0025_00/scene0025_00_vh_clean_2.ply
#   raw_instance_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0025_00/scene0025_00.aggregation.json
#   raw_label_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0025_00/scene0025_00_vh_clean_2.labels.ply
#   raw_segmentation_filepath: /home/samanti/Desktop/data_practice/raw/scans/scene0025_00/scene0025_00_vh_clean_2.0.010000.segs.json
#   scene: 25
#   scene_type: Office
#   sub_scene: 0
